version: '3.8'

services:
  db-postgres-resort:
    image: "postgres"
    container_name: db-resort-ctn
    ports:
      - "5001:5432"
    volumes:
      - db-data-resort:/var/lib/postgresql/data
    networks:
      - resort-net
    environment:
      POSTGRES_DB: dbresort
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped

  resort-service:
    build: .
    image: resort-service-img
    container_name: resort-service-ctn
    ports:
      - "8081:8080"
    depends_on:
      - db-postgres-resort
    networks:
      - resort-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres-resort:5432/dbresort
volumes:
  db-data-resort:
networks:
  resort-net:
    driver: bridge