INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (1, 'molto fantasioso', 4, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (2, 'Buon cibo, ma servizio lento.', 3, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (3, 'Vista spettacolare!', 5, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (4, 'Stanze pulite e accoglienti.', 4, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (5, 'Personale cordiale e disponibile.', 5, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (6, 'Camere rumorose di notte.', 2, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (7, 'Cibo mediocre, ma posizione fantastica.', 3, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (8, 'Servizio clienti pessimo.', 1, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (9, 'Atmosfera tranquilla e rilassante.', 5, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (10, 'Prezzi eccessivi per quello che offrono.', 2, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (11, 'Molte attività per tutta la famiglia.', 4, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (12, 'Bella piscina, ma sporca.', 2, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (13, 'Eccellente servizio e personale cortese.', 5, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (14, 'Mancanza di pulizia nelle camere.', 2, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (15, 'Colazione deliziosa con molte opzioni.', 4, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (16, 'Vicino a tutte le attrazioni principali.', 4, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (17, 'Bagni sporchi e mal mantenuti.', 1, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (18, 'Check-in veloce e processuale.', 5, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (19, 'Vicino a una bellissima spiaggia.', 5, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (20, 'Wifi instabile e lento.', 2, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (21, 'Rumori fastidiosi di notte.', 1, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (22, 'Prezzi ragionevoli e conveniente.', 4, 2);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (23, 'Personale gentile, ma stanze vecchie.', 3, 4);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (24, 'Bella vista dal balcone.', 5, 9);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (25, 'Ristorante con cibo delizioso.', 4, 8);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (26, 'Servizio in camera efficiente.', 4, 9);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (27, 'Piscina ben curata e pulita.', 5, 9);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (28, 'Rumori fastidiosi provenienti dalla strada.', 2, 9);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (29, 'Posizione comoda per i trasporti pubblici.', 3, 7);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (30, 'Colazione varia e abbondante.', 4, 11);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (31, 'Wifi gratuito ma instabile.', 2, 10);
INSERT INTO public.reviews (id, description, rating, resort_id) VALUES (32, 'Personale disponibile a fornire informazioni turistiche.', 5, 6);
