server:
  port: ${API_GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: resort-route
          uri: http://${RESORT_SERVICE_HOST:localhost}/${RESORT_SERVICE_PORT:8080}
          predicates:
            - Path=/resorts/**
          filters:
            - PrefixPath=/api/v1
        - id: resort-reservation-route
          uri: http://${RESORT_RESERVATION_SERVICE_HOST:localhost}/${RESORT_RESERVATION_SERVICE_PORT:8080}
          predicates:
            - Path=/resort-reservations/**
          filters:
            - PrefixPath=/api/v1
        - id: review-route
          uri: http://${REVIEW_SERVICE_HOST:localhost}/${REVIEW_SERVICE_PORT:8080}
          predicates:
            - Path=/reviews/**
          filters:
            - PrefixPath=/api/v1
      discovery:
        locator:
          enabled: true

  # Configurazione Config Server
  config:
    import: optional:configserver:http://localhost:8888

# Configurazione Eureka Server
eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/