# syntax=docker/dockerfile:1
# Stage 1: Build Angular application
FROM node:latest AS builder
WORKDIR /usr/app
# Copy package.json and package-lock.json
COPY package*.json .
# Install dependencies
RUN npm install
# Copy the rest of the application
COPY . .
# Build the Angular application
RUN npm run build -- --prod

# Stage 2: Serve the built application
FROM nginx:latest
# Copy the built Angular app from the builder stage
COPY --from=builder /app/dist /usr/share/nginx/html
# Expose port 80
EXPOSE 80
# Default command to run Nginx
CMD ["nginx", "-g", "daemon off;"]