networks:
  event-net:
    driver: bridge
  global-net:
    driver: bridge
  resort-net:
    driver: bridge
  resort-reservation-net:
    driver: bridge
  review-net:
    driver: bridge
services:
  api-gateway:
    container_name: api-gateway-ctn
    environment:
      API_GATEWAY_HOST: api-gateway
      API_GATEWAY_PORT: '8080'
      EUREKA_SERVER_HOST: eureka-discovery-server
      EUREKA_SERVER_PORT: '8761'
      EVENT_SERVICE_HOST: event-service
      EVENT_SERVICE_PORT: '8084'
      RESORT_RESERVATION_SERVICE_HOST: resort-reservation-service
      RESORT_RESERVATION_SERVICE_PORT: '8082'
      RESORT_SERVICE_HOST: resort-service
      RESORT_SERVICE_PORT: '8081'
      REVIEW_SERVICE_HOST: review-service
      REVIEW_SERVICE_PORT: '8083'
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: '9411'
    image: seeyousun/api-gateway:1.0
    networks:
      global-net: null
    ports:
    - published: 8080
      target: 8080
  db-postgres-event:
    container_name: db-event-ctn
    environment:
      POSTGRES_DB: dbevent
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      restart: unless-stopped
    image: postgres
    networks:
      event-net: null
    ports:
    - published: 5004
      target: 5432
    volumes:
    - db-data-event:/var/lib/postgresql/data:rw
  db-postgres-resort:
    container_name: db-resort-ctn
    environment:
      POSTGRES_DB: dbresort
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      restart: unless-stopped
    image: postgres
    networks:
      resort-net: null
    ports:
    - published: 5001
      target: 5432
    volumes:
    - db-data-resort:/var/lib/postgresql/data:rw
  db-postgres-resort-reservation:
    container_name: db-resort-reservation-ctn
    environment:
      POSTGRES_DB: dbresortreservation
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      restart: unless-stopped
    image: postgres
    networks:
      resort-reservation-net: null
    ports:
    - published: 5002
      target: 5432
    volumes:
    - db-data-resort-reservation:/var/lib/postgresql/data:rw
  db-postgres-review:
    container_name: db-review-ctn
    environment:
      POSTGRES_DB: dbreview
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      restart: unless-stopped
    image: postgres
    networks:
      review-net: null
    ports:
    - published: 5003
      target: 5432
    volumes:
    - db-data-review:/var/lib/postgresql/data:rw
  eureka-discovery-server:
    container_name: eureka-discovery-server-ctn
    environment:
      EUREKA_SERVER_HOST: eureka-discovery-server
      EUREKA_SERVER_PORT: '8761'
    image: seeyousun/eureka-discovery-server:1.0
    networks:
      global-net: null
    ports:
    - published: 8761
      target: 8761
  event-service:
    container_name: event-service-ctn
    environment:
      DATABASE_HOST: db-postgres-event
      DATABASE_NAME: dbevent
      DATABASE_PORT: '5004'
      EUREKA_SERVER_HOST: eureka-discovery-server
      EUREKA_SERVER_PORT: '8761'
      EVENT_SERVICE_HOST: event-service
      EVENT_SERVICE_PORT: '8084'
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: '9411'
    image: seeyousun/event-service:1.0
    networks:
      event-net: null
      global-net: null
    ports:
    - published: 8084
      target: 8084
  frontend-app:
    container_name: frontend-app-ctn
    image: seeyousun/frontend-app:1.0
    networks:
      global-net: null
    ports:
    - published: 4200
      target: 4200
    volumes:
    - /home/emanuele/Documenti/uni/magistrale/primo_anno/taass/progetto_esame/frontend-app:/usr/app:rw
    - /usr/app/node_modules
  rabbit-mq:
    container_name: rabbit-mq-ctn
    image: rabbitmq:3-management-alpine
    networks:
      global-net: null
    ports:
    - published: 5672
      target: 5672
    - published: 15672
      target: 15672
    volumes:
    - source: data-rabbit-mq
      target: /var/lib/rabbitmq
      type: volume
  resort-reservation-service:
    container_name: resort-reservation-service-ctn
    environment:
      DATABASE_HOST: db-postgres-resort-reservation
      DATABASE_NAME: dbresortreservation
      DATABASE_PORT: '5002'
      EUREKA_SERVER_HOST: eureka-discovery-server
      EUREKA_SERVER_PORT: '8761'
      RESORT_RESERVATION_SERVICE_HOST: resort-reservation-service
      RESORT_RESERVATION_SERVICE_PORT: '8082'
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: '9411'
    image: seeyousun/resort-reservation-service:1.0
    networks:
      global-net: null
      resort-reservation-net: null
    ports:
    - published: 8082
      target: 8082
  resort-service:
    container_name: resort-service-ctn
    environment:
      DATABASE_HOST: db-postgres-resort
      DATABASE_NAME: dbresort
      DATABASE_PORT: '5001'
      EUREKA_SERVER_HOST: eureka-discovery-server
      EUREKA_SERVER_PORT: '8761'
      RABBIT_HOST: rabbit-mq
      RABBIT_PASSWORD: guest
      RABBIT_PORT: '5672'
      RABBIT_USERNAME: guest
      RESORT_SERVICE_HOST: resort-service
      RESORT_SERVICE_PORT: '8081'
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: '9411'
    image: seeyousun/resort-service:1.0
    networks:
      global-net: null
      resort-net: null
    ports:
    - published: 8081
      target: 8081
  review-service:
    container_name: review-service-ctn
    environment:
      DATABASE_HOST: db-postgres-review
      DATABASE_NAME: dbreview
      DATABASE_PORT: '5003'
      EUREKA_SERVER_HOST: eureka-discovery-server
      EUREKA_SERVER_PORT: '8761'
      RABBIT_HOST: rabbit-mq
      RABBIT_PASSWORD: guest
      RABBIT_PORT: '5672'
      RABBIT_USERNAME: guest
      REVIEW_SERVICE_HOST: review-service
      REVIEW_SERVICE_PORT: '8083'
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: '9411'
    image: seeyousun/review-service:1.0
    networks:
      global-net: null
      review-net: null
    ports:
    - published: 8083
      target: 8083
  zipkin:
    container_name: zipkin-ctn
    image: openzipkin/zipkin
    networks:
      global-net: null
    ports:
    - published: 9411
      target: 9411
version: '3.2'
volumes:
  data-rabbit-mq: {}
  db-data-event: {}
  db-data-resort: {}
  db-data-resort-reservation: {}
  db-data-review: {}

