###
GET http://localhost:8080/resorts/v1/popular

###
GET http://localhost:8080/resorts/v1/getResortByName/aaa

###
GET http://localhost:8080/resorts/v1/getResortByLocation/rivoli

###
GET http://localhost:8080/resorts/v1/getResortById/1

###
GET http://localhost:8080/resorts/v1/getAllService


