version: '3.8'
services:
  resort-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: resort-service:latest
    container_name: resort-service-ctn
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - resort-network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: resort
      POSTGRES_USER: resort
      POSTGRES_PASSWORD: resort
    restart: unless-stopped
    networks:
      - resort-network
    volumes:
      - postgresdb-data-resort:/data

networks:
  resort-network:
volumes:
  postgresdb-data-resort: