version: '3'

services:
  dbpostgresql:
    image: "postgres"
    container_name: db-resort-ctn
    ports:
      - "5001:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - net
    environment:
      POSTGRES_DB: dbresort
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped

  resortservice:
    build: .
    image: resort-service-img
    container_name: resort-service-ctn
    ports:
      - "8081:8080"
    depends_on:
      - dbpostgresql
    networks:
      - net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql:5432/dbresort
volumes:
  db-data:
networks:
  net:
    driver: bridge