version: '3'

services:
  dbpostgresql:
    image: "postgres"
    container_name: db-resort-reservation-ctn
    ports:
      - "5002:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - net
    environment:
      POSTGRES_DB: dbresortreservation
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped

  resortreservationservice:
    build: .
    image: resort-reservation-service-img
    container_name: resort-reservation-service-ctn
    ports:
      - "8082:8080"
    depends_on:
      - dbpostgresql
    networks:
      - net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresql:5432/dbresortreservation

volumes:
  db-data:
networks:
  net:
    driver: bridge