INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (1, '2024-01-06', 1);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (64, '2024-01-14', 1);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (65, '2024-01-15', 1);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (66, '2024-01-16', 1);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (67, '2024-01-17', 1);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (68, '2024-01-18', 1);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (69, '2024-01-19', 1);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (70, '2024-01-20', 1);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (71, '2024-01-21', 1);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (72, '2024-01-22', 1);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (73, '2024-01-23', 1);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (74, '2024-01-24', 1);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (75, '2024-01-14', 2);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (76, '2024-01-15', 2);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (77, '2024-01-16', 2);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (78, '2024-01-17', 2);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (79, '2024-01-18', 2);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (80, '2024-01-19', 2);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (81, '2024-01-20', 2);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (82, '2024-01-21', 2);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (83, '2024-01-22', 2);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (84, '2024-01-23', 2);
INSERT INTO public.daily_reservations (id, date, resort_id) VALUES (85, '2024-01-24', 2);

INSERT INTO public.reservations (id, number_of_sunbeds, persistence_type_enum, reserved_umbrella_column, reserved_umbrella_line, user_uid, daily_reservation_id) VALUES (1, 2, 'FULL_DAY', 1, 1, 'adffaefc', 79);
INSERT INTO public.reservations (id, number_of_sunbeds, persistence_type_enum, reserved_umbrella_column, reserved_umbrella_line, user_uid, daily_reservation_id) VALUES (2, 2, 'FULL_DAY', 1, 2, 'fadfadsfa', 79);
INSERT INTO public.reservations (id, number_of_sunbeds, persistence_type_enum, reserved_umbrella_column, reserved_umbrella_line, user_uid, daily_reservation_id) VALUES (3, 2, 'HALF_DAY_MORNING', 1, 3, 'dfssf', 79);
INSERT INTO public.reservations (id, number_of_sunbeds, persistence_type_enum, reserved_umbrella_column, reserved_umbrella_line, user_uid, daily_reservation_id) VALUES (4, 3, 'HALF_DAY_AFTERNOON', 1, 3, 'gferwf', 79);
