spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
      client:
        registration:
          google:
            client-id: 36727298504-httkr5ka2ua2h3goiv93aj7tdcn620mh.apps.googleusercontent.com
            client-secret: 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