server:
  port: 8080

spring:
  application:
    name: review-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    url: jdbc:postgresql://${DATABASE_SERVICE_HOST:localhost}:${DATABASE_SERVICE_PORT:5432}/${DATABASE_NAME:default}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never

  # Configurazione Config Server
  config:
    import: optional:configserver:http://localhost:8888

  # Configurazione RabbitMQ
  rabbitmq:
    host: ${RABBIT_SERVICE_HOST:localhost}
    port: ${RABBIT_SERVICE_PORT:localhost}
    username: ${RABBIT_SERVICE_USERNAME:guest}
    password: ${RABBIT_SERVICE_PASSWORD:guest}

# Configurazione Eureka Discovery Server
eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka