INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2024-02-05', 'Fantasioso e incantevole', 4, 1, 'Un sogno nel verde', 'adgwegf', 'Alice');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2024-02-05', 'Buon cibo, ma servizio lento.', 3, 1, 'Gusto con calma', 'adgwegf', 'Bob');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2024-02-05', 'Vista spettacolare!', 5, 1, 'Panorama mozzafiato', 'adgwegf', 'Charlie');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2024-02-05', 'Stanze pulite e accoglienti.', 4, 1, 'Comfort a misura di viaggiatore', 'adgwegf', 'David');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2024-02-05', 'Personale cordiale e disponibile.', 5, 1, 'Ospitalità premurosa', 'adgwegf', 'Emma');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2024-02-05', 'Camere rumorose di notte.', 2, 1, 'Silenzio disturbato', 'adgwegf', 'Frank');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2024-02-05', 'Cibo mediocre, ma posizione fantastica.', 3, 2, 'Tra gusto e vista', 'adgwegf', 'Grace');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2023-02-05', 'Servizio clienti pessimo.', 1, 2, 'Personale del resort odioso', 'adgwegf', 'Henry');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2022-02-05', 'Atmosfera tranquilla e rilassante.', 5, 2, 'Piacevole posto', 'adgwegf', 'Isabella');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2023-01-15','Prezzi eccessivi per quello che offrono.', 2, 2, 'Costoso', 'adgwegf', 'Jack');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2022-11-25', 'Molte attività per tutta la famiglia.', 4, 2, 'Bello', 'adgwegf', 'Katherine');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2023-04-13', 'Bella piscina, ma sporca.', 2, 2, 'Si trova di meglio', 'adgwegf', 'Leo');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2024-06-01', 'Eccellente servizio e personale cortese.', 5, 2, 'Eccellente', 'adgwegf', 'Mia');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2023-03-11', 'Mancanza di pulizia nelle camere.', 2, 2, 'Sporca', 'adgwegf', 'Nathan');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2023-07-12', 'Colazione deliziosa con molte opzioni.', 4, 2, 'Delizioso', 'adgwegf', 'Olivia');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2023-08-05', 'Vicino a tutte le attrazioni principali.', 4, 2, 'Comodo', 'adgwegf', 'Peter');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2023-05-15', 'Bagni sporchi e mal mantenuti.', 1, 2, 'Maltenuto', 'adgwegf', 'Quinn');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2023-09-13', 'Check-in veloce e processuale.', 5, 2, 'Rapido', 'adgwegf', 'Rachel');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2023-02-15', 'Vicino a una bellissima spiaggia.', 5, 2, 'Comodo', 'adgwegf', 'Sam');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2023-01-17', 'Wifi instabile e lento.', 2, 2, 'Servizi insufficienti', 'adgwegf', 'Tina');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2021-01-12', 'Rumori fastidiosi di notte.', 1, 2, 'Molto rumoroso', 'adgwegf', 'Victor');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2022-08-19', 'Prezzi ragionevoli e conveniente.', 4, 2, 'Economico', 'adgwegf', 'Wendy');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2022-12-11', 'Personale gentile, ma stanze vecchie.', 3, 4, 'Gentili', 'adgwegf', 'Xavier');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2021-01-05', 'Bella vista dal balcone.', 5, 9, 'Ottima vista', 'adgwegf', 'Yvonne');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2021-08-03', 'Ristorante con cibo delizioso.', 4, 8, 'Cibo buono', 'adgwegf', 'Zane');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2023-07-12', 'Servizio in camera efficiente.', 4, 9, 'Efficienti', 'adgwegf', 'Alice');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2023-03-05', 'Piscina ben curata e pulita.', 5, 9, 'Ottima cura', 'adgwegf', 'Bob');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2022-04-01', 'Rumori fastidiosi provenienti dalla strada.', 2, 9, 'Rumoroso', 'adgwegf', 'Charlie');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2022-05-14', 'Posizione comoda per i trasporti pubblici.', 3, 7, 'Trasporti vicini', 'adgwegf', 'David');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2021-06-25', 'Colazione varia e abbondante.', 4, 11, 'Ottima colazione', 'adgwegf', 'Emma');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2021-02-05', 'Wifi gratuito ma instabile.', 2, 10, 'Wifi migliorabile', 'adgwegf', 'Frank');
INSERT INTO public.reviews (date, body_review, rating, resort_id, title, user_uid, username) VALUES ('2022-05-15', 'Personale disponibile a fornire informazioni turistiche.', 5, 6, 'Disponibilità ottima', 'adgwegf', 'Grace');
