INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (1, '2024-02-05', 'Fantasioso e incantevole', 4, 1, 'Un sogno nel verde');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (2, '2024-02-05', 'Buon cibo, ma servizio lento.', 3, 1, 'Gusto con calma');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (3, '2024-02-05', 'Vista spettacolare!', 5, 1, 'Panorama mozzafiato');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (4, '2024-02-05', 'Stanze pulite e accoglienti.', 4, 1, 'Comfort a misura di viaggiatore');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (5, '2024-02-05', 'Personale cordiale e disponibile.', 5, 1, 'Ospitalità premurosa');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (6, '2024-02-05', 'Camere rumorose di notte.', 2, 1, 'Silenzio disturbato');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (7, '2024-02-05', 'Cibo mediocre, ma posizione fantastica.', 3, 2, 'Tra gusto e vista');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (8, '2023-02-05', 'Servizio clienti pessimo.', 1, 2, 'Personale del resort odioso');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (9, '2022-02-05', 'Atmosfera tranquilla e rilassante.', 5, 2, 'Piacevole posto');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (10, '2023-01-15','Prezzi eccessivi per quello che offrono.', 2, 2, 'Costoso');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (11, '2022-11-25', 'Molte attività per tutta la famiglia.', 4, 2, 'Bello');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (12, '2023-04-13', 'Bella piscina, ma sporca.', 2, 2, 'Si trova di meglio');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (13, '2024-06-01', 'Eccellente servizio e personale cortese.', 5, 2, 'Eccellente');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (14, '2023-03-11', 'Mancanza di pulizia nelle camere.', 2, 2, 'Sporca');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (15, '2023-07-12', 'Colazione deliziosa con molte opzioni.', 4, 2, 'Delizioso');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (16, '2023-08-05', 'Vicino a tutte le attrazioni principali.', 4, 2, 'Comodo');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (17, '2023-05-15', 'Bagni sporchi e mal mantenuti.', 1, 2, 'Maltenuto');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (18, '2023-09-13', 'Check-in veloce e processuale.', 5, 2, 'Rapido');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (19, '2023-02-15', 'Vicino a una bellissima spiaggia.', 5, 2, 'Comodo');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (20, '2023-01-17', 'Wifi instabile e lento.', 2, 2, 'Servizi insufficienti');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (21, '2021-01-12', 'Rumori fastidiosi di notte.', 1, 2, 'Molto rumoroso');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (22, '2022-08-19', 'Prezzi ragionevoli e conveniente.', 4, 2, 'Economico');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (23, '2022-12-11', 'Personale gentile, ma stanze vecchie.', 3, 4, 'Gentili');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (24, '2021-01-05', 'Bella vista dal balcone.', 5, 9, 'Ottima vista');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (25, '2021-08-03', 'Ristorante con cibo delizioso.', 4, 8, 'Cibo buono');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (26, '2023-07-12', 'Servizio in camera efficiente.', 4, 9, 'Efficienti');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (27, '2023-03-05', 'Piscina ben curata e pulita.', 5, 9, 'Ottima cura');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (28, '2022-04-01', 'Rumori fastidiosi provenienti dalla strada.', 2, 9, 'Rumoroso');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (29, '2022-05-14', 'Posizione comoda per i trasporti pubblici.', 3, 7, 'Trasporti vicini');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (30, '2021-06-25', 'Colazione varia e abbondante.', 4, 11, 'Ottima colazione');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (31, '2021-02-05', 'Wifi gratuito ma instabile.', 2, 10, 'Wifi migliorabile');
INSERT INTO public.reviews (id, date, description, rating, resort_id, title) VALUES (32, '2022-05-15', 'Personale disponibile a fornire informazioni turistiche.', 5, 6, 'Disponibilità ottima');
