server:
  port: ${EUREKA_SERVER_PORT:8761}
spring:
  application:
    name: eureka-discovery-server
  # Configurazione del Config Server: se non viene trovato salta questo passaggio senza crashare grazie ad "optional"
  config:
    import: optional:configserver:http://localhost:8888
# Configurazione Eureka Server ed Eureka Client
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/