server:
  port: ${EUREKA_SERVER_PORT:8761}
spring:
  application:
    name: eureka-discovery-server
# Configurazione Eureka Server ed Eureka Client
eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
    # prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka
# Configurazione del Config Server: se non viene trovato salta questo passaggio senza crashare grazie ad "optional"
# spring:
#   config:
#     import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8888}