//da Home 1.0 a Home1.1
###
GET http://localhost:8080/resorts/v1/popular

//da Home 1.0 a Home1.1 ricerca per Nome
###
GET http://localhost:8080/resorts/v1/resort-by-name/Mar

//da Home 1.0 a Home1.1 ricerca per Location
###
GET http://localhost:8080/resorts/v1/resort-by-location/Galli

###
//da Home 1.0 a Home1.1 ricerca per Location e Service
POST http://localhost:8080/resorts/v1
Content-Type: application/json

{
  "services": [{"name":"IDROMASSAGGIO", "category": "Benessere"}, {"name":"BAR", "category": "Ristorazione"}],
  "location": "Gallipo"
}

###
//da Home 1.1 a ResortPage
GET http://localhost:8080/resorts/v1/resort-by-id/2

###
GET http://localhost:8082/api/v1/resort-reservations/information/2/2024-01-16




