version: '3.8'


services:
  api-gateway:
    build: ./api-gateway
    image: api-gateway-img
    container_name: api-gateway-ctn
    ports:
      - "8080:8080"
    networks:
      - global-net
    environment:
      - RESORT_SERVICE_HOST=resort-service
      - RESORT_SERVICE_PORT=8080
      - RESORT_RESERVATION_SERVICE_HOST=resort-reservation-service
      - RESORT_RESERVATION_SERVICE_PORT=8080
      - REVIEW_SERVICE_HOST=review-service
      - REVIEW_SERVICE_PORT=8080

  # EUREKA DISCOVERY SERVER
  discovery-server:
    build: ./eureka-discovery-server
    image: eureka-discovery-server-img
    container_name: eureka-discovery-server-ctn
    ports:
      - "8761:8761"
    networks:
      - global-net

  # RABBIT-MQ
  rabbit-mq:
    image: rabbitmq:3-management-alpine
    container_name: rabbit-mq-ctn
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - global-net

  # DATABASE RESORT-SERVICE
  db-postgres-resort:
    image: "postgres"
    container_name: db-resort-ctn
    ports:
      - "5001:5432"
    volumes:
      - db-data-resort:/var/lib/postgresql/data
    networks:
      - resort-net
    environment:
      POSTGRES_DB: dbresort
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      restart: unless-stopped

  # RESORT-SERVICE
  resort-service:
    build: ./resort-service
    image: resort-service-img
    container_name: resort-service-ctn
    ports:
      - "8081:8080"
    depends_on:
      - discovery-server
      - db-postgres-resort
    networks:
      - resort-net
      - global-net
    environment:
      - EUREKA_SERVER_HOST=${EUREKA_SERVER_HOST}
      - EUREKA_SERVER_PORT=${EUREKA_SERVER_PORT}
      - RABBIT_SERVICE_HOST=${RABBIT_SERVICE_HOST}
      - RABBIT_SERVICE_PORT=${RABBIT_SERVICE_PORT}
      - RABBIT_SERVICE_USERNAME=${RABBIT_SERVICE_USERNAME}
      - RABBIT_SERVICE_PASSWORD=${RABBIT_SERVICE_PASSWORD}
      - DATABASE_SERVICE_HOST=db-postgres-resort
      - DATABASE_SERVICE_PORT=5432
      - DATABASE_NAME=dbresort

  # DATABASE RESORT-RESERVATION-SERVICE
  db-postgres-resort-reservation:
    image: "postgres"
    container_name: db-resort-reservation-ctn
    ports:
      - "5002:5432"
    volumes:
      - db-data-resort-reservation:/var/lib/postgresql/data
    networks:
      - resort-reservation-net
    environment:
      POSTGRES_DB: dbresortreservation
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      restart: unless-stopped

  # RESORT-RESERVATION-SERVICE
  resort-reservation-service:
    build: ./resort-reservation-service
    image: resort-reservation-service-img
    container_name: resort-reservation-service-ctn
    ports:
      - "8082:8080"
    depends_on:
      - discovery-server
      - db-postgres-resort-reservation
    networks:
      - resort-reservation-net
      - global-net
    environment:
      - EUREKA_SERVER_HOST=${EUREKA_SERVER_HOST}
      - EUREKA_SERVER_PORT=${EUREKA_SERVER_PORT}
      - DATABASE_SERVICE_HOST=db-postgres-resort-reservation
      - DATABASE_SERVICE_PORT=5432
      - DATABASE_NAME=dbresortreservation

  # DATABASE REVIEW-SERVICE
  db-postgres-review:
    image: "postgres"
    container_name: db-review-ctn
    ports:
      - "5003:5432"
    volumes:
      - db-data-review:/var/lib/postgresql/data
    networks:
      - review-net
    environment:
      POSTGRES_DB: dbreview
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      restart: unless-stopped

  # REVIEW-SERVICE
  review-service:
    build: ./review-service
    image: review-service-img
    container_name: review-service-ctn
    ports:
      - "8083:8080"
    depends_on:
      - discovery-server
      - db-postgres-review
    networks:
      - review-net
      - global-net
    environment:
      - EUREKA_SERVER_HOST=${EUREKA_SERVER_HOST}
      - EUREKA_SERVER_PORT=${EUREKA_SERVER_PORT}
      - RABBIT_SERVICE_HOST=${RABBIT_SERVICE_HOST}
      - RABBIT_SERVICE_PORT=${RABBIT_SERVICE_PORT}
      - RABBIT_SERVICE_USERNAME=${RABBIT_SERVICE_USERNAME}
      - RABBIT_SERVICE_PASSWORD=${RABBIT_SERVICE_PASSWORD}
      - DATABASE_SERVICE_HOST=db-postgres-review
      - DATABASE_SERVICE_PORT=5432
      - DATABASE_NAME=dbreview

volumes:
  db-data-resort:
  db-data-resort-reservation:
  db-data-review:
networks:
  global-net:
    driver: bridge
  resort-net:
    driver: bridge
  resort-reservation-net:
    driver: bridge
  review-net:
    driver: bridge