version: '3.8'

services:
  # eureka server
  discovery-server:
    build: ./eureka-discovery-server
    image: eureka-discovery-server-img
    container_name: eureka-discovery-server-ctn
    ports:
      - "8761:8761"
    networks:
      - global_net
    environment:
      - EUREKA_INSTANCE_HOSTNAME=discovery-server
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka

  # resort-service DB
  dbpostgresresort:
    image: "postgres"
    container_name: db-resort-ctn
    ports:
      - "5001:5432"
    volumes:
      - resort_db_data:/var/lib/postgresql/data
    networks:
      - resort_net
    environment:
      POSTGRES_DB: dbresort
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped

  # resort-service
  resortservice:
      build: ./resort-service
      image: resort-service-img
      container_name: resort-service-ctn
      ports:
        - "8081:8080"
      depends_on:
        - discovery-server
        - dbpostgresresort
      networks:
        - resort_net
        - global_net
      environment:
        - EUREKA_INSTANCE_HOSTNAME=discovery-server
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
        - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgresresort:5432/dbresort
volumes:
  resort_db_data:
networks:
  global_net:
    driver: bridge
  resort_net:
    driver: bridge